In [27]:
import pandas as pd

In [28]:
df_hwc = pd.read_csv('../datasets/exoplanet_hwc.csv')
df_hwc.head()

,P_NAME,P_DETECTION,P_DISCOVERY_FACILITY,P_YEAR,P_UPDATE,P_MASS,P_MASS_ERROR_MIN,P_MASS_ERROR_MAX,P_MASS_LIMIT,P_MASS_ORIGIN,...,S_ABIO_ZONE,S_TIDAL_LOCK,P_HABZONE_OPT,P_HABZONE_CON,P_TYPE_TEMP,P_HABITABLE,P_ESI,S_CONSTELLATION,S_CONSTELLATION_ABR,S_CONSTELLATION_ENG
0,OGLE-2016-BLG-1227L b,Microlensing,OGLE,2020,2020-04-02,250.00,-120.0,413.0,0,Mass,...,NaN,0.214133,0,0,NaN,0,NaN,Scorpius,Sco,Scorpion
1,Kepler-276 c,Transit,Kepler,2013,2018-09-25,16.60,-3.6,4.4,0,Mass,...,2.097783,0.316980,0,0,Hot,0,0.272032,Cygnus,Cyg,Swan
2,Kepler-829 b,Transit,Kepler,2016,2019-04-16,5.10,NaN,NaN,0,M-R relationship,...,1.756317,0.459559,0,0,Hot,0,0.254763,Lyra,Lyr,Lyre
3,K2-283 b,Transit,K2,2018,2019-09-05,12.20,NaN,NaN,0,M-R relationship,...,0.568374,0.443760,0,0,Hot,0,0.193906,Pisces,Psc,Fishes
4,Kepler-477 b,Transit,Kepler,2016,2019-04-16,4.94,NaN,NaN,0,M-R relationship,...,0.768502,0.386150,0,0,Hot,0,0.276721,Lyra,Lyr,Lyre

In [29]:
df_nasa = pd.read_csv('../datasets/exoplanet_nasa.csv', comment='#')
df_nasa.head()

,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,pl_orbpererr1,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,11 Com b,11 Com,2,1,Radial Velocity,2007.0,Xinglong Station,0,323.21000,0.06,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,11 UMi b,11 UMi,1,1,Radial Velocity,2009.0,Thueringer Landessternwarte Tautenburg,0,516.21997,3.20,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,14 And b,14 And,1,1,Radial Velocity,2008.0,Okayama Astrophysical Observatory,0,186.76000,0.11,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,14 Her b,14 Her,1,2,Radial Velocity,2002.0,W. M. Keck Observatory,0,1766.41000,0.67,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996.0,Multiple Observatories,0,798.50000,1.00,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

In [30]:
print(df_nasa.shape)
print(df_nasa.columns)
print(df_nasa.dtypes)
print(df_nasa.describe())

(6291, 84)
Index(['pl_name', 'hostname', 'sy_snum', 'sy_pnum', 'discoverymethod',
       'disc_year', 'disc_facility', 'pl_controv_flag', 'pl_orbper',
       'pl_orbpererr1', 'pl_orbpererr2', 'pl_orbperlim', 'pl_orbsmax',
       'pl_orbsmaxerr1', 'pl_orbsmaxerr2', 'pl_orbsmaxlim', 'pl_rade',
       'pl_radeerr1', 'pl_radeerr2', 'pl_radelim', 'pl_radj', 'pl_radjerr1',
       'pl_radjerr2', 'pl_radjlim', 'pl_bmasse', 'pl_bmasseerr1',
       'pl_bmasseerr2', 'pl_bmasselim', 'pl_bmassj', 'pl_bmassjerr1',
       'pl_bmassjerr2', 'pl_bmassjlim', 'pl_bmassprov', 'pl_orbeccen',
       'pl_orbeccenerr1', 'pl_orbeccenerr2', 'pl_orbeccenlim', 'pl_insol',
       'pl_insolerr1', 'pl_insolerr2', 'pl_insollim', 'pl_eqt', 'pl_eqterr1',
       'pl_eqterr2', 'pl_eqtlim', 'ttv_flag', 'st_spectype', 'st_teff',
       'st_tefferr1', 'st_tefferr2', 'st_tefflim', 'st_rad', 'st_raderr1',
       'st_raderr2', 'st_radlim', 'st_mass', 'st_masserr1', 'st_masserr2',
       'st_masslim', 'st_met', 'st_meterr1', 'st_meterr2', 'st_metlim',
       'st_metratio', 'st_logg', 'st_loggerr1', 'st_loggerr2', 'st_logglim',
       'rastr', 'ra', 'decstr', 'dec', 'sy_dist', 'sy_disterr1', 'sy_disterr2',
       'sy_vmag', 'sy_vmagerr1', 'sy_vmagerr2', 'sy_kmag', 'sy_kmagerr1',
       'sy_kmagerr2', 'sy_gaiamag', 'sy_gaiamagerr1', 'sy_gaiamagerr2'],
      dtype='str')
pl_name                str
hostname               str
sy_snum              int64
sy_pnum              int64
discoverymethod        str
                    ...
sy_kmagerr1        float64
sy_kmagerr2        float64
sy_gaiamag         float64
sy_gaiamagerr1     float64
sy_gaiamagerr2     float64
Length: 84, dtype: object
           sy_snum      sy_pnum    disc_year  pl_controv_flag     pl_orbper  \
count  6291.000000  6291.000000  6290.000000      6291.000000  5.951000e+03
mean      1.101733     1.762995  2017.189984         0.008584  7.192974e+04
std       0.339946     1.152975     5.087530         0.092257  5.213558e+06
min       1.000000     1.000000  1992.000000         0.000000  9.070629e-02
25%       1.000000     1.000000  2014.000000         0.000000  4.302702e+00
50%       1.000000     1.000000  2016.000000         0.000000  1.068157e+01
75%       1.000000     2.000000  2021.000000         0.000000  3.800714e+01
max       4.000000     8.000000  2026.000000         1.000000  4.020000e+08

       pl_orbpererr1  pl_orbpererr2  pl_orbperlim    pl_orbsmax  \
count   5.462000e+03   5.462000e+03   5951.000000   5866.000000
mean    8.764458e+04  -2.002025e+04     -0.001008     15.644242
std     6.359799e+06   1.355102e+06      0.031739    348.091198
min     0.000000e+00  -1.000000e+08     -1.000000      0.004400
25%     1.200000e-05  -1.399000e-03      0.000000      0.052300
50%     8.191500e-05  -8.200000e-05      0.000000      0.102050
75%     1.382525e-03  -1.200000e-05      0.000000      0.304575
max     4.700000e+08   0.000000e+00      0.000000  19000.000000

       pl_orbsmaxerr1  ...  sy_disterr2      sy_vmag  sy_vmagerr1  \
count     3929.000000  ...  6156.000000  5992.000000  5984.000000
mean         1.797244  ...   -66.310410    12.541111     0.097132
std         83.242975  ...   277.653561     3.031350     0.134542
min          0.000000  ... -2840.000000     0.872000     0.001000
25%          0.000710  ...   -16.211000    10.701000     0.030000
50%          0.002000  ...    -3.721000    13.190500     0.069000
75%          0.015500  ...    -0.420500    14.915000     0.126000
max       5205.000000  ...    -0.000350    44.610000     3.100000

       sy_vmagerr2      sy_kmag  sy_kmagerr1  sy_kmagerr2   sy_gaiamag  \
count  5979.000000  6005.000000  5968.000000  5957.000000  5948.000000
mean     -0.098593    10.371520     0.040948    -0.040962    12.248129
std       0.199712     2.961935     0.250464     0.256273     2.930209
min     -11.920000    -3.044000     0.011000    -9.995000     2.364310
25%      -0.126000     8.408000     0.020000    -0.030000    10.425075
50%      -0.069000    11.055000     0.023000    -0.023000    12.917450
75%      -0.030000    12.706000     0.030000    -0.020000    14.660275
max      -0.001000    33.110000     9.995000    -0.011000    20.186100

       sy_gaiamagerr1  sy_gaiamagerr2
count     5948.000000     5948.000000
mean         0.000636       -0.000636
std          0.001782        0.001782
min          0.000112       -0.063232
25%          0.000257       -0.000539
50%          0.000364       -0.000364
75%          0.000539       -0.000257
max          0.063232       -0.000112

[8 rows x 75 columns]

In [31]:
print(df_hwc.shape)
print(df_hwc.columns)
print(df_hwc.dtypes)
print(df_hwc.describe())

(5599, 118)
Index(['P_NAME', 'P_DETECTION', 'P_DISCOVERY_FACILITY', 'P_YEAR', 'P_UPDATE',
       'P_MASS', 'P_MASS_ERROR_MIN', 'P_MASS_ERROR_MAX', 'P_MASS_LIMIT',
       'P_MASS_ORIGIN',
       ...
       'S_ABIO_ZONE', 'S_TIDAL_LOCK', 'P_HABZONE_OPT', 'P_HABZONE_CON',
       'P_TYPE_TEMP', 'P_HABITABLE', 'P_ESI', 'S_CONSTELLATION',
       'S_CONSTELLATION_ABR', 'S_CONSTELLATION_ENG'],
      dtype='str', length=118)
P_NAME                      str
P_DETECTION                 str
P_DISCOVERY_FACILITY        str
P_YEAR                    int64
P_UPDATE                    str
                         ...
P_HABITABLE               int64
P_ESI                   float64
S_CONSTELLATION             str
S_CONSTELLATION_ABR         str
S_CONSTELLATION_ENG         str
Length: 118, dtype: object
            P_YEAR        P_MASS  P_MASS_ERROR_MIN  P_MASS_ERROR_MAX  \
count  5599.000000   5592.000000       2506.000000       2506.000000
mean   2016.188962    442.521283       -127.777520        174.465166
std       4.527714   2369.505048        383.670428        625.151645
min    1992.000000      0.020000      -6038.739700          0.000000
25%    2014.000000      4.040000        -73.100900          2.712500
50%    2016.000000      8.750000        -19.069800         20.000000
75%    2020.000000    162.092490         -2.542630         85.813670
max    2024.000000  89700.000000          0.000000      12395.308000

       P_MASS_LIMIT     P_RADIUS  P_RADIUS_ERROR_MIN  P_RADIUS_ERROR_MAX  \
count   5599.000000  5592.000000         3847.000000         3847.000000
mean       0.022861     5.715494           -0.432279            0.544259
std        0.160982     5.331450            0.960669            1.568228
min       -1.000000     0.310000          -32.506000            0.000000
25%        0.000000     1.780000           -0.480000            0.130000
50%        0.000000     2.780000           -0.220000            0.280000
75%        0.000000    11.900000           -0.110000            0.581500
max        1.000000    77.342000            0.000000           68.910000

       P_RADIUS_LIMIT      P_PERIOD  ...  S_HZ_CON0_MAX  S_HZ_CON1_MIN  \
count     5599.000000  5.350000e+03  ...    5366.000000    5366.000000
mean        -0.000714  7.994082e+04  ...       2.301153       1.239781
std          0.026721  5.498596e+06  ...       4.587874       2.390133
min         -1.000000  9.070629e-02  ...       0.001910       0.000911
25%          0.000000  4.465382e+00  ...       1.060687       0.568834
50%          0.000000  1.156951e+01  ...       1.561742       0.854147
75%          0.000000  4.150555e+01  ...       2.364700       1.299225
max          0.000000  4.020000e+08  ...     120.348830      67.331558

       S_HZ_CON1_MAX  S_SNOW_LINE   S_ABIO_ZONE  S_TIDAL_LOCK  P_HABZONE_OPT  \
count    5366.000000  5366.000000  5.376000e+03   5595.000000    5599.000000
mean        2.301153     3.596167  1.014471e+35      0.425790       0.047151
std         4.587874     6.741964  5.259131e+36      0.077064       0.211981
min         0.001910     0.002434  4.356319e-05      0.029269       0.000000
25%         1.060687     1.615711  4.781093e-01      0.391256       0.000000
50%         1.561742     2.502441  1.361846e+00      0.443760       0.000000
75%         2.364700     3.873593  2.556535e+00      0.470516       0.000000
max       120.348830   214.468620  2.726899e+38      1.003328       1.000000

       P_HABZONE_CON  P_HABITABLE        P_ESI
count    5599.000000  5599.000000  5358.000000
mean        0.033577     0.019825     0.257089
std         0.180155     0.184617     0.131622
min         0.000000     0.000000     0.023896
25%         0.000000     0.000000     0.186192
50%         0.000000     0.000000     0.268055
75%         0.000000     0.000000     0.301299
max         1.000000     2.000000     0.968362

[8 rows x 99 columns]

In [32]:
master_df = pd.merge(df_nasa, df_hwc, left_on='pl_name', right_on='P_NAME', how='inner')
final_df = master_df[[
    'pl_name',
    'pl_rade',   
    'pl_bmasse', 
    'pl_eqt',     
    'pl_orbsmax',  
    'pl_orbeccen', 
    'st_teff',     
    'sy_snum', 
    'P_ESI'
]]
final_df.shape

(5566, 9)

In [34]:
final_df.isnull().sum()

pl_name           0
pl_rade          46
pl_bmasse        30
pl_eqt         1409
pl_orbsmax      257
pl_orbeccen     720
st_teff         218
sy_snum           0
P_ESI           240
dtype: int64